spring:
  application:
    name: zuul-app

server:
  port: 8080

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://admin:admin@${EUREKA_HOST:127.0.0.1}:8761/eureka/

zuul:
  strip-prefix: false
  routes:
    page:
      path: /page/**
      serviceId: pages-app
      strip-prefix: false
    crawler:
      path: /crawler/**
      serviceId: crawler-app
      strip-prefix: false
    search:
      path: /search/**
      serviceId: searcher-app
      strip-prefix: false
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000

ribbon:
  eureka:
    enabled: true

# Disable Hystrix timeout globally (for all services)
#hystrix.command.default.execution.timeout.enabled: false

# Disable Hystrix timeout for a single service
#hystrix.command.<serviceName>.execution.timeout.enabled: false

# Increase the Hystrix timeout to 60s (globally)
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000

# Increase the Hystrix timeout to 60s (per service)
#hystrix.command.<serviceName>.execution.isolation.thread.timeoutInMilliseconds: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

