zuul:
  strip-prefix: false
  routes:
    page:
      path: /page/**
      serviceId: pages-app
      strip-prefix: false
    crawler:
      path: /crawler/**
      serviceId: crawler-app
      strip-prefix: false
    search:
      path: /search/**
      serviceId: searcher-app
      strip-prefix: false
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000

ribbon:
  eureka:
    enabled: true


